In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import experimenter
import pandas as pd 
import matplotlib.pyplot as plt 

sns.set_theme()

In [4]:
KNATIVE_EXPERIMENT_NAME = "exps/20230319_140118.feather"

def process_experiment(filename):
    data_df = pd.read_feather(filename)

    data_df["api_server_creation_delta"] = data_df["event_created_at"] - data_df["before_create_timestamp"]
    data_df["api_server_deletion_delta"] = data_df["event_deleted_at"] - data_df["before_delete_timestamp"]

    data_df["api_creation_delta"] = data_df["last_created_at"] - data_df["first_created_at"]
    data_df["api_scheduled_delta"] = data_df["last_scheduled_at"] - data_df["first_scheduled_at"]

    # ADD OTHER TIME DELTA CALCULATIONS HERE
    
    data_df.to_feather(filename)
    return data_df

knative_minikube_df = process_experiment(KNATIVE_EXPERIMENT_NAME)
# knative_minikube_df.columns
knative_minikube_df

,before_create_timestamp,before_firstwait_timestamp,before_delete_timestamp,before_secondwait_timestamp,before_cooldown_timestamp,before_join_timestamp,replicas,framework,error_occured,errors_rised,...,event_replicas_at,first_created_at,last_created_at,first_deleted_at,last_deleted_at,first_scheduled_at,last_scheduled_at,api_server_creation_delta,api_server_deletion_delta,api_scheduler_creation_delta
0,2023-03-19 14:01:18.699598,2023-03-19 14:01:18.763986,2023-03-19 14:01:26.060849,2023-03-19 14:01:26.109787,2023-03-19 14:01:26.109801,2023-03-19 14:01:28.112024,1,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0]",2023-03-19 14:01:18.974245,2023-03-19 14:01:18.974245,2023-03-19 14:01:59.733790,2023-03-19 14:01:59.733790,2023-03-19 14:01:19.078481,2023-03-19 14:01:19.078481,0 days 00:00:00.059754,0 days 00:00:00.048505,0 days 00:00:00
1,2023-03-19 14:02:00.242157,2023-03-19 14:02:00.373655,2023-03-19 14:02:08.415676,2023-03-19 14:02:08.467478,2023-03-19 14:02:08.467495,2023-03-19 14:02:10.469725,1,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0]",2023-03-19 14:02:00.491877,2023-03-19 14:02:00.491877,2023-03-19 14:02:42.347538,2023-03-19 14:02:42.347538,2023-03-19 14:02:00.593186,2023-03-19 14:02:00.593186,0 days 00:00:00.127642,0 days 00:00:00.051367,0 days 00:00:00
2,2023-03-19 14:02:42.856002,2023-03-19 14:02:42.920685,2023-03-19 14:02:51.323795,2023-03-19 14:02:51.383125,2023-03-19 14:02:51.383142,2023-03-19 14:02:53.385350,1,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0]",2023-03-19 14:02:43.051339,2023-03-19 14:02:43.051339,2023-03-19 14:03:25.787403,2023-03-19 14:03:25.787403,2023-03-19 14:02:43.109150,2023-03-19 14:02:43.109150,0 days 00:00:00.059188,0 days 00:00:00.058965,0 days 00:00:00
3,2023-03-19 14:03:26.295237,2023-03-19 14:03:26.354577,2023-03-19 14:03:34.957097,2023-03-19 14:03:35.084617,2023-03-19 14:03:35.084633,2023-03-19 14:03:37.085805,1,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0]",2023-03-19 14:03:26.476114,2023-03-19 14:03:26.476114,2023-03-19 14:04:08.053596,2023-03-19 14:04:08.053596,2023-03-19 14:03:26.533137,2023-03-19 14:03:26.533137,0 days 00:00:00.054928,0 days 00:00:00.126585,0 days 00:00:00
4,2023-03-19 14:04:08.562301,2023-03-19 14:04:08.637838,2023-03-19 14:04:16.083684,2023-03-19 14:04:16.133818,2023-03-19 14:04:16.133835,2023-03-19 14:04:18.135658,1,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0]",2023-03-19 14:04:08.848116,2023-03-19 14:04:08.848116,2023-03-19 14:04:50.129307,2023-03-19 14:04:50.129307,2023-03-19 14:04:08.856129,2023-03-19 14:04:08.856129,0 days 00:00:00.070054,0 days 00:00:00.049655,0 days 00:00:00
5,2023-03-19 14:04:50.768149,2023-03-19 14:04:50.839070,2023-03-19 14:05:12.748149,2023-03-19 14:05:12.795980,2023-03-19 14:05:12.796001,2023-03-19 14:05:14.798174,4,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0]",2023-03-19 14:04:51.012756,2023-03-19 14:04:51.232536,2023-03-19 14:05:49.061797,2023-03-19 14:05:49.855342,2023-03-19 14:04:51.151924,2023-03-19 14:04:51.351910,0 days 00:00:00.070354,0 days 00:00:00.046648,0 days 00:00:00.219780
6,2023-03-19 14:05:50.363867,2023-03-19 14:05:50.428860,2023-03-19 14:06:07.798488,2023-03-19 14:06:07.854273,2023-03-19 14:06:07.854290,2023-03-19 14:06:09.855900,4,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0]",2023-03-19 14:05:50.551355,2023-03-19 14:05:50.702867,2023-03-19 14:06:44.176509,2023-03-19 14:06:44.862940,2023-03-19 14:05:50.620538,2023-03-19 14:05:50.768605,0 days 00:00:00.059711,0 days 00:00:00.060031,0 days 00:00:00.151512
7,2023-03-19 14:06:45.371143,2023-03-19 14:06:45.578184,2023-03-19 14:07:03.740759,2023-03-19 14:07:03.802008,2023-03-19 14:07:03.802030,2023-03-19 14:07:05.804220,4,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0]",2023-03-19 14:06:45.886658,2023-03-19 14:06:46.092897,2023-03-19 14:07:38.190555,2023-03-19 14:07:39.779840,2023-03-19 14:06:46.029481,2023-03-19 14:06:46.233854,0 days 00:00:00.200532,0 days 00:00:00.060406,0 days 00:00:00.206239
8,2023-03-19 14:07:40.287763,2023-03-19 14:07:40.399554,2023-03-19 14:07:59.546274,2023-03-19 14:07:59.594097,2023-03-19 14:07:59.594113,2023-03-19 14:08:01.596286,4,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0]",2023-03-19 14:07:40.537015,2023-03-19 14:07:40.747156,2023-03-19 14:08:35.141715,2023-03-19 14:08:36.349830,2023-03-19 14:07:40.591218,2023-03-19 14:07:40.784400,0 days 00:00:00.106610,0 days 00:00:00.049809,0 days 00:00:00.210141
9,2023-03-19 14:08:36.857381,2023-03-19 14:08:36.915270,2023-03-19 14:08:54.985052,2023-03-19 14:08:55.033456,2023-03-19 14:08:55.033474,2023-03-19 14:08:57.035666,4,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0]",2023-03-19 14:08:37.039283,2023-03-19 14:08:37.229817,2023-03-19 14:09:29.828859,2023-03-19 14:09:30.886323,2023-03-19 14:08:37.090937,2023-03-19 14:08:37.278288,0 days 00:00:00.052043,0 days 00:00:00.047468,0 days 00:00:00.190534
10,2023-03-19 14:09:31.560848,2023-03-19 14:09:31.627200,2023-03-19 14:10:23.161031,2023-03-19 14:10:23.375011,2023-03-19 14:10:23.375034,2023-03-19 14:10:25.375897,13,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, ...",2023-03-19 14:09:32.367232,2023-03-19 14:09:33.121518,2023-03-19 14:11:03.374390,2023-03-19 14:11:13.056267,2023-03-19 14:09:32.573741,2023-03-19 14:09:33.407303,0 days 00:00:00.061345,0 days 00:00:00.211758,0 days 00:00:00.754286
11,2023-03-19 14:11:13.563960,2023-03-19 14:11:13.622706,2023-03-19 14:12:00.209624,2023-03-19 14:12:00.253083,2023-03-19 14:12:00.253103,2023-03-19 14:12:02.255296,13,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, ...",2023-03-19 14:11:13.896743,2023-03-19 14:11:14.364216,2023-03-19 14:12:43.214931,2023-03-19 14:12:51.094444,2023-03-19 14:11:13.937417,2023-03-19 14:11:14.597850,0 days 00:00:00.052710,0 days 00:00:00.045558,0 days 00:00:00.467473
12,2023-03-19 14:12:51.602808,2023-03-19 14:12:51.659939,2023-03-19 14:13:40.195883,2023-03-19 14:13:40.257320,2023-03-19 14:13:40.257337,2023-03-19 14:13:42.259548,13,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, ...",2023-03-19 14:12:51.767360,2023-03-19 14:12:52.206387,2023-03-19 14:14:24.390718,2023-03-19 14:14:31.985214,2023-03-19 14:12:51.809257,2023-03-19 14:12:52.414841,0 days 00:00:00.051530,0 days 00:00:00.060980,0 days 00:00:00.439027
13,2023-03-19 14:14:32.494076,2023-03-19 14:14:32.547806,2023-03-19 14:15:23.494959,2023-03-19 14:15:23.688793,2023-03-19 14:15:23.688809,2023-03-19 14:15:25.689061,13,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, ...",2023-03-19 14:14:32.681308,2023-03-19 14:14:33.291893,2023-03-19 14:16:06.390674,2023-03-19 14:16:13.270568,2023-03-19 14:14:32.725866,2023-03-19 14:14:33.473730,0 days 00:00:00.047647,0 days 00:00:00.193380,0 days 00:00:00.610585
14,2023-03-19 14:16:13.778824,2023-03-19 14:16:13.877721,2023-03-19 14:16:59.782190,2023-03-19 14:16:59.834911,2023-03-19 14:16:59.834933,2023-03-19 14:17:01.835919,13,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, ...",2023-03-19 14:16:13.963753,2023-03-19 14:16:14.352350,2023-03-19 14:17:46.640452,2023-03-19 14:17:55.956475,2023-03-19 14:16:14.086508,2023-03-19 14:16:14.574290,0 days 00:00:00.091948,0 days 00:00:00.052162,0 days 00:00:00.388597
15,2023-03-19 14:17:56.562741,2023-03-19 14:17:56.681299,2023-03-19 14:19:59.680063,2023-03-19 14:19:59.803209,2023-03-19 14:19:59.803225,2023-03-19 14:20:01.803929,36,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, ...",2023-03-19 14:17:57.312827,2023-03-19 14:17:59.836020,2023-03-19 14:20:57.697937,2023-03-19 14:21:32.442620,2023-03-19 14:17:57.520100,2023-03-19 14:18:00.929095,0 days 00:00:00.112288,0 days 00:00:00.124707,0 days 00:00:02.523193
16,2023-03-19 14:21:32.950296,2023-03-19 14:21:33.042120,2023-03-19 14:23:37.481140,2023-03-19 14:23:37.552411,2023-03-19 14:23:37.552430,2023-03-19 14:23:39.554613,36,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, ...",2023-03-19 14:21:33.120864,2023-03-19 14:21:35.456198,2023-03-19 14:24:42.362195,2023-03-19 14:25:04.182921,2023-03-19 14:21:33.271715,2023-03-19 14:21:36.554606,0 days 00:00:00.084763,0 days 00:00:00.070127,0 days 00:00:02.335334
17,2023-03-19 14:25:04.691237,2023-03-19 14:25:04.969860,2023-03-19 14:27:22.482867,2023-03-19 14:27:22.538925,2023-03-19 14:27:22.538942,2023-03-19 14:27:24.539953,36,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, ...",2023-03-19 14:25:05.102166,2023-03-19 14:25:06.499199,2023-03-19 14:28:31.096229,2023-03-19 14:28:53.046917,2023-03-19 14:25:05.131294,2023-03-19 14:25:07.146955,0 days 00:00:00.287625,0 days 00:00:00.055525,0 days 00:00:01.397033
18,2023-03-19 14:28:53.555683,2023-03-19 14:28:53.632197,2023-03-19 14:31:05.299337,2023-03-19 14:31:05.359613,2023-03-19 14:31:05.359630,2023-03-19 14:31:07.361801,36,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, ...",2023-03-19 14:28:53.759226,2023-03-19 14:28:55.630831,2023-03-19 14:32:16.478110,2023-03-19 14:32:37.168015,2023-03-19 14:28:53.794611,2023-03-19 14:28:56.485012,0 days 00:00:00.076155,0 days 00:00:00.059834,0 days 00:00:01.871605
19,2023-03-19 14:32:37.676088,2023-03-19 14:32:37.752172,2023-03-19 14:34:44.477004,2023-03-19 14:34:44.530424,2023-03-19 14:34:44.530445,2023-03-19 14:34:46.532684,36,native,False,"[None, None, None]",...,"[nan, nan, nan, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, ...",2023-03-19 14:32:37.873155,2023-03-19 14:32:39.307924,2023-03-19 14:35:42.683062,2023-03-19 14:36:16.555202,2023-03-19 14:32:37.908640,2023-03-19 14:32:40.289953,0 days 00:00:00.075570,0 days 00:00:00.052914,0 days 00:00:01.434769

In [17]:
knative_minikube_df.api_scheduler_creation_delta

0   0 days 00:00:00.064746
Name: api_scheduler_creation_delta, dtype: timedelta64[ns]

In [ ]:
# # BETTER PROCESS THIS DATA
# plt.figure(figsize=(20, 4))
# plt.subplot(1, 2, 1)
# plt.plot(knative_minikube_df["api_server_deletion_delta"]); plt.title("Creation Times")
# plt.subplot(1, 2, 2)
# plt.plot(knative_minikube_df["api_server_creation_delta"]); plt.title("Deletion Times")
# plt.show()

In [ ]:
# def draw_replicas(replicas=REPLICAS):
#     plt.figure(figsize=(8, 4))
#     plt.plot(range(len(replicas)), replicas)
#     plt.title("Replica Count by Experiments")
#     plt.xlabel("Experiment")
#     plt.ylabel("Replicas")
#     plt.show()

# draw_replicas()
# print(COOLDOWNS)
# print(REPLICAS)